---
- hosts: staging:production
  remote_user: "{{ root_user }}"
  roles:
    - role: common.remote

- hosts: all
  remote_user: "{{ user }}"
  vars:
    node_dir: "/home/{{ user }}"
  roles:
    - role: common
    - role: webserver
    - role: webassets

- hosts: staging:production
  remote_user: "{{ user }}"
  sudo_user: "{{ user }}"
  vars:
    node_dir: "/home/{{ user }}"
    base_dir: "{{ app_dir | dirname }}"
    repo_version: "master"
  roles:
    - role: deploy
